### ISSUE TITLE
Should c# Code Go Here?

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/GeoPoseSandbox#9] opened 2023-01-13 21:05 UTC
In meeting 90 today, I agreed to post an integrated C# implementation of OGC GeoPose v1.0 that I am using in the glTF encoding of the CityGML semantic model with the OS Street Drone test area AKA OS Southampton HQ as a working example (long sentence!). Looking at this repo for the first time, it doesn't really seem to fit it. I did post it in the Implementations section of the main GeoPose [repo](https://github.com/opengeospatial/GeoPose/blob/main/Implementations/glTF/src/GeoPose.cs) . 

If you want it in the Sandbox repo, I can do that too, but please give me a good location.

**Comment by cperey** [comment] 2023-01-15 16:15
@3DXScape I think where you've put it is excellent. Thank you! 

@MikelSalazar and Jan-Erik: since you are working on the code for Sandbox project, please confirm that you know where Steve's C# implementation is and you can get to it (it can be accessed in the implementations directory) when you need it.

Once you have confirmed that you can see/know where that is, please close this issue. Thank you!

**Comment by 3DXScape** [comment] 2023-01-15 23:01
I just posted a second C# implementation that is functionally equivalent to the first, but which unifies the structure of all GeoPoses as having two parts: **Frame Transform** and **Orientation**. This has two advantages

1. it follows the conceptual model explicitly without any hidden parts, such as how the LTP-ENU transform only has the Position parameters as a specification and
2. it makes it easier to design and insert new Frame Specification types into the code.

We actually have been using this second one in the glTF work even though they are (so far) equivalent.

**Closed as completed** 2023-11-10 09:29 UTC
